// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrhutqzkiogazoaugksp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyaHV0cXpraW9nYXpvYXVna3NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMDgzMjAsImV4cCI6MjA1NTY4NDMyMH0.H3BwnPPXqWdmXCJkM2qkpD1zPdDOJAK-iKoZsfpiADg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);